### ISSUE TITLE
use settimeout in mocked functions by default to simulate filemaker's async nature.

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm-mock#6]
When you call a script via `FileMaker.PerformScript[WithOption]`, JS does not wait for the response by default. It's a void function. 

So all mocked scripts should simulate this by wrapping any code in a `setTimeout()` with a very low timeoutInMs setting, perhaps like 5ms or even 0ms. The point isn't to simulate slow performance, but just to move the mock function response to the end of the event loop.

**Comment by dansmith65** [comment]
Might not want to use a timeout of 0ms, apparently "most browsers" don't support it: https://gist.github.com/pthrasher/3105469

**Comment by jwillinghalpern** [comment]
@dansmith65 that looks pretty old (2012) and even the MDN docs reference using timeout of 0 as allowed.

That said, I tested Chrome, Firefox, and Safari and Firefox does behave a little different. It seems to run the timeout function before it returns the timeout id returned by setTimeout.

I had no idea. Here's the JS i ran in each browser console to test:

```javascript
function fn(){console.log('hello')};
setTimeout(fn, 0);
```

**Comment by dansmith65** [comment]
oops! I must have miss-read the date; I thought it was current.
